In [3]:
import json

our_path3 = r'C:\Users\inny9\Documents\GitHub\wiki_people\wiki_crawling\name_list_2_new.json'

with open(our_path3, 'r') as file:
    name_list = json.load(file)

In [4]:
name_list

['Winston Churchill',
 'Martin Luther King ',
 'Nelson Mandela ',
 'Mahatma Gandhi',
 'Franklin D. Roosevelt',
 'John Paul II',
 'Theodore Roosevelt',
 'Adolf Hitler ',
 'Joseph Stalin',
 'V.I. Lenin',
 'Dwight Eisenhower',
 'Ronald Reagan',
 'Woodrow Wilson ',
 'Margaret Thatcher',
 'Charles de Gaulle',
 'Jawaharlal Nehru',
 'John F Kennedy',
 'Mikhail Gorbachev ',
 'Hilary Clinton',
 'Benazir Bhutto',
 'Desmond Tutu',
 'Ataturk',
 'Boris Yeltsin ',
 'Kofi Annan',
 'Dalai Lama',
 'Aung San Suu Kyi',
 'Lyndon Johnson',
 'Indira Gandhi',
 'Eva Peron',
 'Malcolm X',
 'Tony Blair',
 'Mother Teresa',
 'Eleanor Roosevelt',
 'Rosa Parks ',
 'Princess Diana',
 'Raisa Gorbachev',
 'Abbe Pierre',
 'Albert Einstein',
 'Nikola Tesla',
 'Marie Curie\xa0',
 'Alexander Fleming ',
 'John Logie Baird',
 'Enrico Fermi',
 'Stephen Hawking',
 'Rosalind Franklin',
 'Tim Berners-Lee',
 'Pablo Picasso',
 'Salvador Dali',
 'Coco Chanel ',
 'David Hockney',
 'Edvard Munch',
 'General Patton',
 'T.E. Lawrence ',
 'Douglas Haig',
 'Bernard Montgomery',
 'George Orwell',
 'J.R.R.Tolkien',
 'Oscar Wilde ',
 'Ernest Hemingway',
 'John Steinbeck ',
 'Anne Frank',
 'J.K.Rowling',
 'J.K.Rowling',
 'Virginia Woolf',
 'Germaine Greer',
 'Beatrix Potter',
 'C.S. Lewis ',
 'Wilfred Owens',
 'Gabriela Mistral',
 'John Lennon',
 'Elvis Presley',
 'Michael Jackson',
 'Madonna',
 'Elton John',
 'Bob Geldof',
 'Cliff Richard',
 'Paul McCartney',
 'George Harrison',
 'Elvis Presley',
 'Billie Holiday',
 'Pele',
 'Jesse Owens',
 'Babe Ruth',
 'Muhammed Ali',
 'Roger Bannister',
 'Carl Lewis',
 'Bobby Moore',
 'Sir Donald Bradman',
 'Eddy Merckx',
 'David Beckham',
 'Diego Maradona',
 'Tegla Laroupe',
 'Michael Jordan',
 'Sachin Tendulkar',
 'Billie Jean King',
 'Aryton Senna',
 'Lewis Hamilton',
 'Bill Gates ',
 'Richard Branson',
 'Al Capone',
 'Henry Ford ',
 'Steve Jobs ',
 'Audrey Hepburn',
 'Michael Caine',
 'Richard Burton',
 'Marilyn Monroe',
 'Sir Charlie Chaplin',
 'Alec Guinness',
 'Peter Sellers',
 'Richard Attenborough',
 'Katherine Hepburn',
 'Julie Andrews',
 'Alfred Hitchcock',
 'Walt Disney',
 'Michael Moore',
 'Oprah Winfrey',
 'Jacqueline Kennedy Onassis',
 'Neil Armstrong ',
 'Lord Baden Powell',
 'Sri Aurobindo',
 'Maharishi Mahesh Yogi',
 'Paramahansa Yogananda',
 'Xi Jinping',
 'Barack Obama',
 'Oprah Winfrey',
 'Hillary Clinton',
 'Angela Merkel',
 'Joe Biden',
 'Pope Francis',
 'Jeff Bezos',
 'Tim Cook',
 'Steve Jobs',
 'Christine Lagarde',
 'Narendra Modi',
 'Aung San Suu Kyi',
 'Nancy Pelosi',
 'Bill Clinton',
 'George Clooney',
 'Jamie Dimon',
 'Recep Tayyip Erdoğan',
 'Bill Gates',
 'Hu Jintao',
 'LeBron James',
 'Benjamin Netanyahu',
 'Michelle Obama',
 'Condoleezza Rice',
 'Elizabeth Warren',
 'Janet Yellen',
 'Mark Zuckerberg',
 'Taylor Swift',
 'Adele',
 'Pope Benedict XVI',
 'Beyoncé',
 'Warren Buffett',
 'Catherine, Princess of Wales',
 '14th Dalai Lama',
 'Mario Draghi',
 'Kamala Harris',
 'Bob Iger',
 'John Kerry',
 'Charles Koch',
 'David Koch',
 'Luiz Inácio Lula da Silva',
 'Ma Huateng',
 'Nelson Mandela',
 'Lionel Messi',
 'Rupert Murdoch',
 'Naomi Osaka',
 'Larry Page',
 'Brad Pitt',
 'Ren Zhengfei',
 'Shonda Rhimes',
 'John Roberts',
 'Muqtada al-Sadr',
 'Tiger Woods',
 'Malala Yousafzai',
 'John Maynard Keynes']

In [5]:
len(name_list)

177

In [28]:
categories = ['Politics', 'Academics', 'Entertainment', 'Sports', 'Fine Arts', 'Business']

In [70]:
people_occupations = {
 'Winston Churchill': 'Politics',
 'Martin Luther King': 'Politics',
 'Nelson Mandela': 'Politics',
 'Mahatma Gandhi': 'Politics',
 'Franklin D. Roosevelt': 'Politics',
 'John Paul II': 'Politics',
 'Theodore Roosevelt': 'Politics',
 'Adolf Hitler': 'Politics',
 'Joseph Stalin': 'Politics',
 'V.I. Lenin': 'Politics',
 'Dwight Eisenhower': 'Politics',
 'Ronald Reagan': 'Politics',
 'Woodrow Wilson': 'Politics',
 'Margaret Thatcher': 'Politics',
 'Charles de Gaulle': 'Politics',
 'Jawaharlal Nehru': 'Politics',
 'John F Kennedy': 'Politics',
 'Mikhail Gorbachev': 'Politics',
 'Hilary Clinton': 'Politics',
 'Benazir Bhutto': 'Politics',
 'Desmond Tutu': 'Politics',
 'Ataturk': 'Politics',
 'Boris Yeltsin': 'Politics',
 'Kofi Annan': 'Politics',
 'Dalai Lama': 'Politics',
 'Aung San Suu Kyi': 'Politics',
 'Lyndon Johnson': 'Politics',
 'Indira Gandhi': 'Politics',
 'Eva Peron': 'Politics',
 'Malcolm X': 'Politics',
 'Tony Blair': 'Politics',
 'Mother Teresa': 'Politics',
 'Eleanor Roosevelt': 'Politics',
 'Rosa Parks': 'Politics',
 'Princess Diana': 'Politics',
 'Raisa Gorbachev': 'Politics',
 'Abbe Pierre': 'Politics',
 'Albert Einstein': 'Academics',
 'Nikola Tesla': 'Academics',
 'Marie Curie\xa0': 'Academics',
 'Alexander Fleming': 'Academics',
 'John Logie Baird': 'Academics',
 'Enrico Fermi': 'Academics',
 'Stephen Hawking': 'Academics',
 'Rosalind Franklin': 'Academics',
 'Tim Berners-Lee': 'Academics',
 'Pablo Picasso': 'Fine Arts',
 'Salvador Dali': 'Fine Arts',
 'Coco Chanel': 'Fine Arts',
 'David Hockney': 'Fine Arts',
 'Edvard Munch': 'Fine Arts',
 'General Patton': 'Fine Arts',
 'T.E. Lawrence': 'Fine Arts',
 'Douglas Haig': 'Fine Arts',
 'Bernard Montgomery': 'Fine Arts',
 'George Orwell': 'Fine Arts',
 'J.R.R.Tolkien': 'Fine Arts',
 'Oscar Wilde': 'Fine Arts',
 'Ernest Hemingway': 'Fine Arts',
 'John Steinbeck': 'Fine Arts',
 'Anne Frank': 'Fine Arts',
 'J.K.Rowling': 'Fine Arts',
 'J.K.Rowling': 'Fine Arts',
 'Virginia Woolf': 'Fine Arts',
 'Germaine Greer': 'Fine Arts',
 'Beatrix Potter': 'Fine Arts',
 'C.S. Lewis': 'Fine Arts',
 'Wilfred Owens': 'Fine Arts',
 'Gabriela Mistral': 'Fine Arts',
 'John Lennon': 'Entertainment',
 'Elvis Presley': 'Entertainment',
 'Michael Jackson': 'Entertainment',
 'Madonna': 'Entertainment',
 'Elton John': 'Entertainment',
 'Bob Geldof': 'Entertainment',
 'Cliff Richard': 'Entertainment',
 'Paul McCartney': 'Entertainment',
 'George Harrison': 'Entertainment',
 'Elvis Presley': 'Entertainment',
 'Billie Holiday': 'Entertainment',
 'Pele': 'Sports',
 'Jesse Owens': 'Sports',
 'Babe Ruth': 'Sports',
 'Muhammed Ali': 'Sports',
 'Roger Bannister': 'Sports',
 'Carl Lewis': 'Sports',
 'Bobby Moore': 'Sports',
 'Sir Donald Bradman': 'Sports',
 'Eddy Merckx': 'Sports',
 'David Beckham': 'Sports',
 'Diego Maradona': 'Sports',
 'Tegla Laroupe': 'Sports',
 'Michael Jordan': 'Sports',
 'Sachin Tendulkar': 'Sports',
 'Billie Jean King': 'Sports',
 'Aryton Senna': 'Sports',
 'Lewis Hamilton': 'Sports',
 'Bill Gates': 'Business',
 'Richard Branson': 'Business',
 'Al Capone': 'Business',
 'Henry Ford': 'Business',
 'Steve Jobs': 'Business',
 'Audrey Hepburn': 'Entertainment',
 'Michael Caine': 'Entertainment',
 'Richard Burton': 'Entertainment',
 'Marilyn Monroe': 'Entertainment',
 'Sir Charlie Chaplin': 'Entertainment',
 'Alec Guinness': 'Entertainment',
 'Peter Sellers': 'Entertainment',
 'Richard Attenborough': 'Entertainment',
 'Katherine Hepburn': 'Entertainment',
 'Julie Andrews': 'Entertainment',
 'Alfred Hitchcock': 'Entertainment',
 'Walt Disney': 'Entertainment',
 'Michael Moore': 'Entertainment',
 'Oprah Winfrey': 'Entertainment',
 'Jacqueline Kennedy Onassis': 'Entertainment',
 'Neil Armstrong': 'Academics',
 'Lord Baden Powell': 'Politics',
 'Sri Aurobindo': 'Politics',
 'Maharishi Mahesh Yogi': 'Politics',
 'Paramahansa Yogananda': 'Politics',
 'Xi Jinping': 'Politics',
 'Barack Obama': 'Politics',
 'Oprah Winfrey': 'Entertainment',
 'Hillary Clinton': 'Politics',
 'Angela Merkel': 'Politics',
 'Joe Biden': 'Politics',
 'Pope Francis': 'Politics',
 'Jeff Bezos': 'Business',
 'Tim Cook': 'Business',
 'Steve Jobs': 'Business',
 'Christine Lagarde': 'Business',
 'Narendra Modi': 'Politics',
 'Aung San Suu Kyi': 'Politics',
 'Nancy Pelosi': 'Politics',
 'Bill Clinton': 'Politics',
 'George Clooney': 'Politics',
 'Jamie Dimon': 'Business',
 'Recep Tayyip Erdoğan': 'Politics',
 'Bill Gates': 'Business',
 'Hu Jintao': 'Politics',
 'LeBron James': 'Sports',
 'Benjamin Netanyahu': 'Politics',
 'Michelle Obama': 'Politics',
 'Condoleezza Rice': 'Politics',
 'Elizabeth Warren': 'Politics',
 'Janet Yellen': 'Politics',
 'Mark Zuckerberg': 'Business',
 'Taylor Swift': 'Entertainment',
 'Adele': 'Entertainment',
 'Pope Benedict XVI': 'Politics',
 'Beyonce': 'Entertainment',
 'Warren Buffett': 'Business',
 'Catherine, Princess of Wales': 'Entertainment',
 '14th Dalai Lama': 'Politics',
 'Mario Draghi': 'Politics',
 'Kamala Harris': 'Politics',
 'Bob Iger': 'Business',
 'John Kerry': 'Politics',
 'Charles Koch': 'Business',
 'David Koch': 'Business',
 'Luiz Inácio Lula da Silva': 'Politics',
 'Ma Huateng': 'Business',
 'Nelson Mandela': 'Politics',
 'Lionel Messi': 'Sports',
 'Rupert Murdoch': 'Business',
 'Naomi Osaka': 'Sports',
 'Larry Page': 'Business',
 'Brad Pitt': 'Entertainment',
 'Ren Zhengfei': 'Business',
 'Shonda Rhimes': 'Entertainment',
 'John Roberts': 'Politics',
 'Muqtada al-Sadr': 'Politics',
 'Tiger Woods': 'Sports',
 'Malala Yousafzai': 'Politics',
 'John Maynard Keynes': 'Academics'
}

In [31]:
for i in name_list:
    if i in people_occupations.keys():
        print(f"{i} is here, and their occupation is {people_occupations[i]}")
    else:
        print(f"{i} not here!!!!!!!!!")

Winston Churchill is here, and their occupation is Politics
Martin Luther King  is here, and their occupation is Politics
Nelson Mandela  is here, and their occupation is Politics
Mahatma Gandhi is here, and their occupation is Politics
Franklin D. Roosevelt is here, and their occupation is Politics
John Paul II is here, and their occupation is Politics
Theodore Roosevelt is here, and their occupation is Politics
Adolf Hitler  is here, and their occupation is Politics
Joseph Stalin is here, and their occupation is Politics
V.I. Lenin is here, and their occupation is Politics
Dwight Eisenhower is here, and their occupation is Politics
Ronald Reagan is here, and their occupation is Politics
Woodrow Wilson  is here, and their occupation is Politics
Margaret Thatcher is here, and their occupation is Politics
Charles de Gaulle is here, and their occupation is Politics
Jawaharlal Nehru is here, and their occupation is Politics
John F Kennedy is here, and their occupation is Politics
Mikhail Gorbachev  is here, and their occupation is Politics
Hilary Clinton is here, and their occupation is Politics
Benazir Bhutto is here, and their occupation is Politics
Desmond Tutu is here, and their occupation is Politics
Ataturk is here, and their occupation is Politics
Boris Yeltsin  is here, and their occupation is Politics
Kofi Annan is here, and their occupation is Politics
Dalai Lama is here, and their occupation is Politics
Aung San Suu Kyi is here, and their occupation is Politics
Lyndon Johnson is here, and their occupation is Politics
Indira Gandhi is here, and their occupation is Politics
Eva Peron is here, and their occupation is Politics
Malcolm X is here, and their occupation is Politics
Tony Blair is here, and their occupation is Politics
Mother Teresa is here, and their occupation is Politics
Eleanor Roosevelt is here, and their occupation is Politics
Rosa Parks  is here, and their occupation is Politics
Princess Diana is here, and their occupation is Politics
Raisa Gorbachev is here, and their occupation is Politics
Abbe Pierre is here, and their occupation is Politics
Albert Einstein is here, and their occupation is Academics
Nikola Tesla is here, and their occupation is Academics
Marie Curie  is here, and their occupation is Academics
Alexander Fleming  is here, and their occupation is Academics
John Logie Baird is here, and their occupation is Academics
Enrico Fermi is here, and their occupation is Academics
Stephen Hawking is here, and their occupation is Academics
Rosalind Franklin is here, and their occupation is Academics
Tim Berners-Lee is here, and their occupation is Academics
Pablo Picasso is here, and their occupation is Fine Arts
Salvador Dali is here, and their occupation is Fine Arts
Coco Chanel  is here, and their occupation is Fine Arts
David Hockney is here, and their occupation is Fine Arts
Edvard Munch is here, and their occupation is Fine Arts
General Patton is here, and their occupation is Fine Arts
T.E. Lawrence  is here, and their occupation is Fine Arts
Douglas Haig is here, and their occupation is Fine Arts
Bernard Montgomery is here, and their occupation is Fine Arts
George Orwell is here, and their occupation is Fine Arts
J.R.R.Tolkien is here, and their occupation is Fine Arts
Oscar Wilde  is here, and their occupation is Fine Arts
Ernest Hemingway is here, and their occupation is Fine Arts
John Steinbeck  is here, and their occupation is Fine Arts
Anne Frank is here, and their occupation is Fine Arts
J.K.Rowling is here, and their occupation is Fine Arts
J.K.Rowling is here, and their occupation is Fine Arts
Virginia Woolf is here, and their occupation is Fine Arts
Germaine Greer is here, and their occupation is Fine Arts
Beatrix Potter is here, and their occupation is Fine Arts
C.S. Lewis  is here, and their occupation is Fine Arts
Wilfred Owens is here, and their occupation is Fine Arts
Gabriela Mistral is here, and their occupation is Fine Arts
John Lennon is here, and their occupation is Entertainment
Elvis Presley is here, and their occupation is Entertainment
Michael Jackson is here, and their occupation is Entertainment
Madonna is here, and their occupation is Entertainment
Elton John is here, and their occupation is Entertainment
Bob Geldof is here, and their occupation is Entertainment
Cliff Richard is here, and their occupation is Entertainment
Paul McCartney is here, and their occupation is Entertainment
George Harrison is here, and their occupation is Entertainment
Elvis Presley is here, and their occupation is Entertainment
Billie Holiday is here, and their occupation is Entertainment
Pele is here, and their occupation is Sports
Jesse Owens is here, and their occupation is Sports
Babe Ruth is here, and their occupation is Sports
Muhammed Ali is here, and their occupation is Sports
Roger Bannister is here, and their occupation is Sports
Carl Lewis is here, and their occupation is Sports
Bobby Moore is here, and their occupation is Sports
Sir Donald Bradman is here, and their occupation is Sports
Eddy Merckx is here, and their occupation is Sports
David Beckham is here, and their occupation is Sports
Diego Maradona is here, and their occupation is Sports
Tegla Laroupe is here, and their occupation is Sports
Michael Jordan is here, and their occupation is Sports
Sachin Tendulkar is here, and their occupation is Sports
Billie Jean King is here, and their occupation is Sports
Aryton Senna is here, and their occupation is Sports
Lewis Hamilton is here, and their occupation is Sports
Bill Gates  is here, and their occupation is Business
Richard Branson is here, and their occupation is Business
Al Capone is here, and their occupation is Business
Henry Ford  is here, and their occupation is Business
Steve Jobs  is here, and their occupation is Business
Audrey Hepburn is here, and their occupation is Entertainment
Michael Caine is here, and their occupation is Entertainment
Richard Burton is here, and their occupation is Entertainment
Marilyn Monroe is here, and their occupation is Entertainment
Sir Charlie Chaplin is here, and their occupation is Entertainment
Alec Guinness is here, and their occupation is Entertainment
Peter Sellers is here, and their occupation is Entertainment
Richard Attenborough is here, and their occupation is Entertainment
Katherine Hepburn is here, and their occupation is Entertainment
Julie Andrews is here, and their occupation is Entertainment
Alfred Hitchcock is here, and their occupation is Entertainment
Walt Disney is here, and their occupation is Entertainment
Michael Moore is here, and their occupation is Entertainment
Oprah Winfrey is here, and their occupation is Entertainment
Jacqueline Kennedy Onassis is here, and their occupation is Entertainment
Neil Armstrong  is here, and their occupation is Academics
Lord Baden Powell is here, and their occupation is Politics
Sri Aurobindo is here, and their occupation is Politics
Maharishi Mahesh Yogi is here, and their occupation is Politics
Paramahansa Yogananda is here, and their occupation is Politics
Xi Jinping is here, and their occupation is Politics
Barack Obama is here, and their occupation is Politics
Oprah Winfrey is here, and their occupation is Entertainment
Hillary Clinton is here, and their occupation is Politics
Angela Merkel is here, and their occupation is Politics
Joe Biden is here, and their occupation is Politics
Pope Francis is here, and their occupation is Politics
Jeff Bezos is here, and their occupation is Business
Tim Cook is here, and their occupation is Business
Steve Jobs is here, and their occupation is Business
Christine Lagarde is here, and their occupation is Business
Narendra Modi is here, and their occupation is Politics
Aung San Suu Kyi is here, and their occupation is Politics
Nancy Pelosi is here, and their occupation is Politics
Bill Clinton is here, and their occupation is Politics
George Clooney is here, and their occupation is Politics
Jamie Dimon is here, and their occupation is Business
Recep Tayyip Erdoğan is here, and their occupation is Politics
Bill Gates is here, and their occupation is Business
Hu Jintao is here, and their occupation is Politics
LeBron James is here, and their occupation is Sports
Benjamin Netanyahu is here, and their occupation is Politics
Michelle Obama is here, and their occupation is Politics
Condoleezza Rice is here, and their occupation is Politics
Elizabeth Warren is here, and their occupation is Politics
Janet Yellen is here, and their occupation is Politics
Mark Zuckerberg is here, and their occupation is Business
Taylor Swift is here, and their occupation is Entertainment
Adele is here, and their occupation is Entertainment
Pope Benedict XVI is here, and their occupation is Politics
Beyoncé is here, and their occupation is Entertainment
Warren Buffett is here, and their occupation is Business
Catherine, Princess of Wales is here, and their occupation is Entertainment
14th Dalai Lama is here, and their occupation is Politics
Mario Draghi is here, and their occupation is Politics
Kamala Harris is here, and their occupation is Politics
Bob Iger is here, and their occupation is Business
John Kerry is here, and their occupation is Politics
Charles Koch is here, and their occupation is Business
David Koch is here, and their occupation is Business
Luiz Inácio Lula da Silva is here, and their occupation is Politics
Ma Huateng is here, and their occupation is Business
Nelson Mandela is here, and their occupation is Politics
Lionel Messi is here, and their occupation is Sports
Rupert Murdoch is here, and their occupation is Business
Naomi Osaka is here, and their occupation is Sports
Larry Page is here, and their occupation is Business
Brad Pitt is here, and their occupation is Entertainment
Ren Zhengfei is here, and their occupation is Business
Shonda Rhimes is here, and their occupation is Entertainment
John Roberts is here, and their occupation is Politics
Muqtada al-Sadr is here, and their occupation is Politics
Tiger Woods is here, and their occupation is Sports
Malala Yousafzai is here, and their occupation is Politics
John Maynard Keynes is here, and their occupation is Academics

In [32]:
for k, v in people_occupations.items():
    if v in categories:
            print("good")
    else:
        print(f"{k}!!!!!!!!!!!!!!!!!!! Wrong category")

good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good
good

In [46]:

import pandas as pd
import glob
import os

# Path to the directory containing CSV files
directory_path = r'C:\Users\inny9\Desktop\drive-download-20231126T084721Z-001/*.csv'  # Replace 'your_directory_path' with your directory path
output_file = 'merged_file.csv'  # Name of the output file

# Get a list of file paths for all CSV files in the directory
file_list = glob.glob(directory_path)

for file in file_list:
    file_name = os.path.basename(file)  # Extract the file name without the path
    df = pd.read_csv(file)  # Read the CSV into a DataFrame
    df['Name'] = str(file_name)[:-4]
    df.to_csv(file, index=False)  # Save the modified DataFrame back to the CSV file

In [47]:


# Create an empty DataFrame to store the merged data
merged_data = pd.DataFrame()

# Loop through each file and concatenate data into the merged_data DataFrame
for file in file_list:
    data = pd.read_csv(file)  # Read each CSV file
    merged_data = pd.concat([merged_data, data], ignore_index=True)  # Concatenate data

# Write the merged data to a new CSV file
merged_data.to_csv(output_file, index=False)

df = pd.read_csv(output_file)
df

,year,age,event,category1,category2,New_Column,Name
0,1937,2,14th Dalai Lama was selected as the tulku of t...,summary,NaN,14th Dalai Lama.csv,14th Dalai Lama
1,1935,0,14th Dalai Lama was born on 6 July 1935 to a f...,Early life and background,NaN,14th Dalai Lama.csv,14th Dalai Lama
2,1940,5,14th Dalai Lama's formal rule as head of the g...,Life as the Dalai Lama,Cooperation and conflicts with the People's Re...,14th Dalai Lama.csv,14th Dalai Lama
3,1954,19,"On 27 September 1954, 14th Dalai Lama was sele...",Life as the Dalai Lama,Cooperation and conflicts with the People's Re...,14th Dalai Lama.csv,14th Dalai Lama
4,1999,64,"In 14th Dalai Lama's essay ""The Ethic of Compa...",Life as the Dalai Lama,"Teaching activities, public talks",14th Dalai Lama.csv,14th Dalai Lama
...,...,...,...,...,...,...,...
1326,1914,51,Henry Ford announced his $5-per-day program on...,Career,Transmission Patent,Henry Ford.csv,Henry Ford
1327,1901,38,Henry Ford maintained an interest in auto raci...,Racing,NaN,Henry Ford.csv,Henry Ford
1328,1996,133,", Henry Ford did make quite an impact on auto ...",Racing,NaN,Henry Ford.csv,Henry Ford
1329,1915,52,Henry Ford had a vacation residence in Fort My...,Personal interests,Florida and Georgia residences and community,Henry Ford.csv,Henry Ford
1330,1936,73,"In 1936, Henry Ford broke ground for a beautif...",Personal interests,Florida and Georgia residences and community,Henry Ford.csv,Henry Ford

In [50]:
new_column = df['Name']  # Extracting the new column

# Dropping the 'New_Column' from its current position
df = df.drop(columns=['Name'])

# Inserting the 'New_Column' at index 0
df.insert(loc=0, column='Name', value=new_column)

df

,Name,year,age,event,category1,category2
0,14th Dalai Lama,1937,2,14th Dalai Lama was selected as the tulku of t...,summary,NaN
1,14th Dalai Lama,1935,0,14th Dalai Lama was born on 6 July 1935 to a f...,Early life and background,NaN
2,14th Dalai Lama,1940,5,14th Dalai Lama's formal rule as head of the g...,Life as the Dalai Lama,Cooperation and conflicts with the People's Re...
3,14th Dalai Lama,1954,19,"On 27 September 1954, 14th Dalai Lama was sele...",Life as the Dalai Lama,Cooperation and conflicts with the People's Re...
4,14th Dalai Lama,1999,64,"In 14th Dalai Lama's essay ""The Ethic of Compa...",Life as the Dalai Lama,"Teaching activities, public talks"
...,...,...,...,...,...,...
1326,Henry Ford,1914,51,Henry Ford announced his $5-per-day program on...,Career,Transmission Patent
1327,Henry Ford,1901,38,Henry Ford maintained an interest in auto raci...,Racing,NaN
1328,Henry Ford,1996,133,", Henry Ford did make quite an impact on auto ...",Racing,NaN
1329,Henry Ford,1915,52,Henry Ford had a vacation residence in Fort My...,Personal interests,Florida and Georgia residences and community
1330,Henry Ford,1936,73,"In 1936, Henry Ford broke ground for a beautif...",Personal interests,Florida and Georgia residences and community

In [52]:
df.to_csv(r'C:\Users\inny9\Desktop\drive-download-20231126T084721Z-001\merged_person.csv', index=False)

In [72]:
# Create a new column based on matching keys from 'Column_0' to the dictionary keys
df['Occupation'] = df['Name'].map(people_occupations)
df = df.drop('Occupations', axis=1)
df

,Name,year,age,event,category1,category2,Occupation
0,14th Dalai Lama,1937,2,14th Dalai Lama was selected as the tulku of t...,summary,NaN,Politics
1,14th Dalai Lama,1935,0,14th Dalai Lama was born on 6 July 1935 to a f...,Early life and background,NaN,Politics
2,14th Dalai Lama,1940,5,14th Dalai Lama's formal rule as head of the g...,Life as the Dalai Lama,Cooperation and conflicts with the People's Re...,Politics
3,14th Dalai Lama,1954,19,"On 27 September 1954, 14th Dalai Lama was sele...",Life as the Dalai Lama,Cooperation and conflicts with the People's Re...,Politics
4,14th Dalai Lama,1999,64,"In 14th Dalai Lama's essay ""The Ethic of Compa...",Life as the Dalai Lama,"Teaching activities, public talks",Politics
...,...,...,...,...,...,...,...
1326,Henry Ford,1914,51,Henry Ford announced his $5-per-day program on...,Career,Transmission Patent,Business
1327,Henry Ford,1901,38,Henry Ford maintained an interest in auto raci...,Racing,NaN,Business
1328,Henry Ford,1996,133,", Henry Ford did make quite an impact on auto ...",Racing,NaN,Business
1329,Henry Ford,1915,52,Henry Ford had a vacation residence in Fort My...,Personal interests,Florida and Georgia residences and community,Business
1330,Henry Ford,1936,73,"In 1936, Henry Ford broke ground for a beautif...",Personal interests,Florida and Georgia residences and community,Business

In [66]:
df

,Name,year,age,event,category1,category2,Occupations
0,14th Dalai Lama,1937,2,14th Dalai Lama was selected as the tulku of t...,summary,NaN,Politics
1,14th Dalai Lama,1935,0,14th Dalai Lama was born on 6 July 1935 to a f...,Early life and background,NaN,Politics
2,14th Dalai Lama,1940,5,14th Dalai Lama's formal rule as head of the g...,Life as the Dalai Lama,Cooperation and conflicts with the People's Re...,Politics
3,14th Dalai Lama,1954,19,"On 27 September 1954, 14th Dalai Lama was sele...",Life as the Dalai Lama,Cooperation and conflicts with the People's Re...,Politics
4,14th Dalai Lama,1999,64,"In 14th Dalai Lama's essay ""The Ethic of Compa...",Life as the Dalai Lama,"Teaching activities, public talks",Politics
...,...,...,...,...,...,...,...
1326,Henry Ford,1914,51,Henry Ford announced his $5-per-day program on...,Career,Transmission Patent,Business
1327,Henry Ford,1901,38,Henry Ford maintained an interest in auto raci...,Racing,NaN,Business
1328,Henry Ford,1996,133,", Henry Ford did make quite an impact on auto ...",Racing,NaN,Business
1329,Henry Ford,1915,52,Henry Ford had a vacation residence in Fort My...,Personal interests,Florida and Georgia residences and community,Business
1330,Henry Ford,1936,73,"In 1936, Henry Ford broke ground for a beautif...",Personal interests,Florida and Georgia residences and community,Business

In [75]:
#check if the occupations are all mapped correctly without omissions
nan_count = df['Occupation'].isna().sum()

# Display the count of NaN values in 'Column_A'
print(f"Number of NaN values in 'Column_A': {nan_count}")

rows_with_nan = df[df['Occupation'].isnull()]
print("Rows with NaN in 'Column_A':")
#rows_with_nan

Number of NaN values in 'Column_A': 0
Rows with NaN in 'Column_A':